env:
  - VERSION=19.3.3
  - VERSION=18.12.17
  - VERSION=18.12.13
  - VERSION=18.10.3
  - VERSION=18.6.0
  - VERSION=18.5.1
  - VERSION=18.4.0
  - VERSION=18.1.0
  - VERSION=1.1.54394
  - VERSION=1.1.54390
  - VERSION=1.1.54388
  - VERSION=1.1.54385
  - VERSION=1.1.54383
#  - VERSION=1.1.54381
#  - VERSION=1.1.54380
#  - VERSION=1.1.54378 client's image miss tzdata package: https://github.com/yandex/ClickHouse/commit/1bf49fe8446c7dea95beaef2b131e6c6708b0b62#diff-cc737435a5ba74620a889b7718f39a80
#  - VERSION=1.1.54343
#  - VERSION=1.1.54342
##  - VERSION=1.1.54337 Broken network
#  - VERSION=1.1.54327
#  - VERSION=1.1.54310
#  - VERSION=1.1.54304
#  - VERSION=1.1.54292
#  - VERSION=1.1.54289
#  - VERSION=1.1.54284
#  - VERSION=1.1.54282

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy2.7-5.8.0"
  - "pypy3.5"
cache: pip
services:
  - docker
before_install:
  - docker run -e "TZ=Europe/Moscow" -d -p 127.0.0.1:9000:9000 --name test-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:$VERSION
  - docker run -d --entrypoint "/bin/sh" --name test-clickhouse-client --link test-clickhouse-server:clickhouse-server yandex/clickhouse-client:$VERSION -c 'while :; do sleep 1; done'
  - docker ps -a
  # Faking clickhouse-client real communication with container via docker exec.
  - echo -e '#!/bin/bash\n\ndocker exec -e "`env | grep ^TZ=`" test-clickhouse-client clickhouse-client "$@"' | sudo tee /usr/local/bin/clickhouse-client > /dev/null
  - sudo chmod +x /usr/local/bin/clickhouse-client
  # Overriding setup.cfg. Set host=clickhouse-server
  - sed -i 's/^host=localhost$/host=clickhouse-server/' setup.cfg
  # Make host think that clickhouse-server is localhost
  - echo '127.0.0.1 clickhouse-server' | sudo tee /etc/hosts > /dev/null
install:
  - pip install --upgrade pip setuptools
  - pip install flake8 flake8-print coveralls
before_script:
  flake8
script:
  coverage run --source=clickhouse_driver setup.py test
after_success:
  coveralls
